added more details in the Github Actions

diff --git a/.github/workflows/proto-schema-compatibility.yml b/.github/workflows/proto-schema-compatibility.yml
--- a/.github/workflows/proto-schema-compatibility.yml
+++ b/.github/workflows/proto-schema-compatibility.yml
@@ -51,4 +51,12 @@ jobs:
     - name: Run ProtoBuf Backward compatibility changes
       run: |
         java -jar schemata.jar isBackwardCompatible -s model.desc -b base-branch/model.desc -p protobuf
+        exit_code=$?
+        if [ $exit_code -eq 0 ]; then
+          echo "ProtoBuf Backward compatibility check passed"
+        else
+          echo "ProtoBuf Backward compatibility check failed"
+          java -jar schemata.jar compatibilitySummary -s model.desc -b base-branch/model.desc -p protobuf
+          exit 1
+        fi
     
